pass profile through metadata['_p']
CDLUC3/ezid pull request #393
Opened 2023-03-09 01:35 UTC by jsjiang

@datadavev @rushirajnenuji Hi Dave and Rushiraj,
The `formRecord` function has two options to get the profile info:
1. through the "profile" parameter of the function
2. through the metadata["_p"] data field

Since the caller `uploadMetadata` does not use the profile parameter, option 2 should be considered.

This change still needs comprehensive tests to cover all datacite related profiles including:
* datacite
* dc
This change should not affect other profiles but tests are also needed.

Test data should cover both name:value and XML formats.

Please let me know if you have questions.

Thank you

Jing

2023-03-09 18:15 UTC, datadavev commented on ezidapp/management/commands/proc-datacite.py
> +        metadata['_p'] = str(ref_id.profile)
I think it's ok to set this property here, but I think it really should be set in the `ref_id.metadata` when the `ref_id` instance is created.

2023-03-09 19:14 UTC, jsjiang commented on ezidapp/management/commands/proc-datacite.py
> +        metadata['_p'] = str(ref_id.profile)
@datadavev Do you mean to save profile as a separate data field in the metadata field, like:
ezidapp_identifier.metadata: 

{
	"_profile": "dc",
	"dc.date": "2023",
	"dc.type": "Dataset",
	"dc.title": "EBL Domain Theories",
	"dc.creator": "test creator",
	"dc.publisher": "UCI Machine Learning Repository"
}

Jing

2023-03-13 19:26 UTC, jsjiang commented
@datadavev @rushirajnenuji Hi Dave and Rushiraj:
Should I use "metadata['_p']" or "metadata['_profile']? 

Jing

2023-03-13 19:38 UTC, datadavev commented on ezidapp/management/commands/proc-datacite.py
> +        metadata['_p'] = str(ref_id.profile)
No. `_profile` is a property of the identifier record, not of the metadata.

My comment above was that I thought the `ref_id.profile` value would be set from the `identifier.profile` value of the corresponding Identifier record.

2023-03-13 19:40 UTC, rushirajnenuji commented
Hey @jsjiang  -- thank you for checking, let's stick with `_profile`? Since that's the keyword users will be supplying in the request body and we've reserved that keyword as [internal metadata](https://ezid.cdlib.org/doc/apidoc.html#internal-metadata).

2023-03-13 19:46 UTC, datadavev requested changes
On further review, I don't think this is correct.

`_p` or `_profile` is set from the `.profile` property of the identifier record when the record is being exported to ANVL or some other format.

I do not believe it is correct to set the `_p` or `_profile` property within the metadata of the record.

2023-03-13 19:57 UTC, datadavev commented
> On further review, I don't think this is correct.
> 
> `_p` or `_profile` is set from the `.profile` property of the identifier record when the record is being exported to ANVL or some other format.
> 
> I do not believe it is correct to set the `_p` or `_profile` property within the metadata of the record.

I have traced through the code, which calls `impl.datacite.uploadMetadata` which in turn calls `formRecord`.

Therein, the "profile" is extracted from the "metadata" dict like:
```
    if profile is None:
        profile = metadata.get("_p", metadata.get("_profile", "erc"))
```
Hence, it is correct to set `_p` or `_profile` in the metadata struct being sent on to `impl.datacite.uploadMetadata`

Apologies for the confusion - but setting either `metadata[_p]` or metadata[_profile]` to the profile property of the `ref_id` record is correct.

2023-03-13 19:58 UTC, datadavev approved these changes
See previous comment - either `_p` or `_profile` works here.

2023-03-15 21:18 UTC, merged